# Use the official Node.js 14 image from DockerHub
FROM node:latest

# Set the working directory
WORKDIR /app

# Copy the rest of your app's source code
COPY . .

# Expose the port the app runs in
EXPOSE 8080
